sudo: false

os:
  - osx

language: node_js
node_js:
  - '8'

addons:
  sauce_connect: true

notifications:
    on_success: always
    on_failure: always

install:
- npm install

before_script:
  - npm install

script:
  - npm run compile
  - npm run test.saucelabs
