sudo: false

os:
  - osx

language: node_js
node_js:
  - '10'

notifications:
    on_success: always
    on_failure: always

install:
- npm install

script:
  - npm run compile
  - npm run test.saucelabs
